'use client';
import { useEffect, useRef, useState } from 'react';
type Event = { second:number; event_type:string; team_side:string; x:number; y:number; description:string };
export default function StickmanSimulation({ events, onDone }: { events: Event[]; onDone: () => void }) {
  const ref = useRef<HTMLDivElement>(null); const [label, setLabel] = useState('킥오프 준비');
  useEffect(() => { let game: import('phaser').Game | undefined; let done = false;
    import('phaser').then(Phaser => { if (!ref.current) return; let players: any[] = []; let ball: any; let timerText: any; let scoreText: any;
      const config: import('phaser').Types.Core.GameConfig = { type: Phaser.AUTO, parent: ref.current, width: 800, height: 450, backgroundColor: '#15803d', scene: { create() { const scene = this as any; scene.add.rectangle(400,225,760,390).setStrokeStyle(3,0xffffff); scene.add.line(400,225,400,30,400,420,0xffffff); scene.add.rectangle(30,225,30,120).setStrokeStyle(3,0xffffff); scene.add.rectangle(770,225,30,120).setStrokeStyle(3,0xffffff); timerText = scene.add.text(20,10,'0s',{fontSize:'22px'}); scoreText = scene.add.text(330,10,'졸라맨 시뮬레이션',{fontSize:'22px'}); for (let i=0;i<5;i++){ players.push(scene.add.circle(180,120+i*50,12,0x2563eb)); players.push(scene.add.circle(620,120+i*50,12,0xef4444)); } ball = scene.add.circle(400,225,8,0xffffff); events.forEach(ev => scene.time.delayedCall(ev.second * 1000, () => { setLabel(ev.description); timerText.setText(`${ev.second}s`); const tx = ev.x * 8; const ty = ev.y * 4.5; scene.tweens.add({ targets: ball, x: tx, y: ty, duration: 800 }); players.forEach((p, idx) => { const dir = ev.team_side === 'home' ? 1 : -1; scene.tweens.add({ targets: p, x: p.x + dir * (idx % 2 ? 22 : 12), y: p.y + ((idx % 3) - 1) * 12, duration: 650, yoyo: true }); }); if (ev.event_type === 'goal') scoreText.setText('GOAL! 졸라맨 골!'); }); }); scene.time.delayedCall(30000, () => { if (!done) { done = true; onDone(); } }); } } }; game = new Phaser.Game(config); }); return () => { done = true; game?.destroy(true); }; }, [events, onDone]);
  return <div><div ref={ref} className="overflow-hidden rounded-2xl border border-emerald-300" /><p className="mt-3 rounded bg-slate-800 p-3 text-emerald-200">{label}</p></div>;
}
